export const projects = [
  {
    title: "medialink CES",
    brand: "medialink",
    type: "digital",
    video: "/videos/marketing-reinvented.mp4",
    img: null,
  },
  {
    title: "converse SoHo",
    brand: "converse",
    type: "environment",
    video: "/videos/converse-soho.mp4",
    img: null,
  },
  {
    title: "run with nike",
    brand: "nike",
    type: "environment",
    img: "/images/work/run-with-nike.webp",
    video: null,
  },
  {
    title: "NYFW popup",
    brand: "afterpay",
    type: "experiential",
    video: "/videos/nyfw-popup.mp4",
    img: null,
  },
  {
    title: "play new kidsvision",
    brand: "nike",
    type: "experiential",
    video: "/videos/play-new-kidsvision.mp4",
    img: null,
  },
  {
    title: "air force 1 2022",
    brand: "nike",
    type: "environment",
    img: "/images/work/airforce-1-2022.webp",
    video: null,
  },
  {
    title: "carmelo anthony 7pm in brooklyn set",
    brand: "wave sports entertainment",
    type: "environment",
    video: "/videos/carmelo-anthony.mp4",
    img: null,
  },
  {
    title: "chicago marathon",
    brand: "nike",
    type: "environment",
    img: "/images/work/chicago-marathon-2022.webp",
    video: null,
  },
  {
    title: "WSE super bowl pregame party",
    brand: "wave sports entertainment",
    type: "experiential",
    video: "/videos/wse-super-bowl.mp4",
    img: null,
  },
  {
    title: "CES 2023",
    brand: "medialink",
    type: "experiential",
    img: "/images/work/ces-2023.webp",
    video: null,
  },
  {
    title: "never done",
    brand: "nike",
    type: "environment",
    img: "/images/work/never-done.webp",
    video: null,
  },
  {
    title: "olympics play new",
    brand: "nike",
    type: "environment",
    img: "/images/work/olympics-play-new.webp",
    video: null,
  },
  {
    title: "MLB all star LA",
    brand: "nike",
    type: "environment",
    img: "/images/work/mlb-all-star-la.webp",
    video: null,
  },
  {
    title: "hunter X nordstrom",
    brand: "hunter",
    type: "experiential",
    video: "/videos/hunter-x-nordstrom.mp4",
    img: null,
  },
  {
    title: "superrep",
    brand: "nike",
    type: "environment",
    img: "/images/work/superrep.webp",
    video: null,
  },
  {
    title: "made for play ",
    brand: "paterson",
    type: "digital",
    img: "/images/work/made-for-play.jpeg",
    video: null,
  },
];
